#!/usr/bin/env bash
# test/check-links.sh — does bootstrap.sh wire this repo the way it says, and stay quiet
# the second time? Generated by dotfiles-core/scripts/new-os-repo.sh; extend it as the
# repo grows (dotfiles-Debian/test/ is the model for what a real suite looks like).
#
# Runs bootstrap.sh three times against a throwaway HOME and asserts:
#   1. --dry-run prints its plan and writes nothing;
#   2. a real run links every repo-owned file to its destination — and the Core-provided
#      ones too, when the vendored core/ carries them;
#   3. a second run changes nothing. Idempotency is the property every later `make check`
#      relies on, and the one a hand-edited bootstrap loses first.
# Needs bash, git (the mise seed assertion compares `git hash-object`) and the usual Unix
# utilities — find, ls, readlink, cksum, awk, sort, stat. No language runtime, no package
# install: every one of those is present on any runner that could have cloned this repo.
# Exit 0 clean, 1 on any failure.
set -uo pipefail
REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd -- "$REPO" || exit 1

# `set -e` is deliberately off (the exit code IS the result), so the sandbox is guarded
# by hand: an empty $tmp would turn "$tmp/home" into /home, and a hermetic test would
# write to the host.
tmp="$(mktemp -d "${TMPDIR:-/tmp}/check-links.XXXXXX")" && [[ -n "$tmp" && -d "$tmp" ]] || { echo "check-links: could not create a temp dir" >&2; exit 1; }
trap 'rm -rf "$tmp"' EXIT
rc=0
ok() { printf '  ok   %s\n' "$*"; }
bad() { printf '  FAIL %s\n' "$*" >&2; rc=1; }

# ── 1. --dry-run touches nothing ─────────────────────────────────────────────
# HOME and XDG_CONFIG_HOME are BOTH pinned under the sandbox on every run: the driver
# honours an exported XDG_CONFIG_HOME (as it should), so a suite that redirected only
# HOME would wire the caller's real config dir on a box that exports it — CI runners do.
mkdir -p "$tmp/dry"
if ! HOME="$tmp/dry" XDG_CONFIG_HOME="$tmp/dry/.config" ./bootstrap.sh --dry-run >"$tmp/dry.out" 2>&1; then
  bad "bootstrap.sh --dry-run exited non-zero: $(cat "$tmp/dry.out")"
fi
# `ls -A`, not `find -quit`: BSD find on macOS lacks -quit, and a failing find would
# substitute EMPTY and pass this assertion for the wrong reason.
if [[ -z "$(ls -A "$tmp/dry")" ]]; then
  ok "--dry-run wrote nothing"
else
  # shellcheck disable=SC2012  # a diagnostic listing of our own temp dir; `find -mindepth` is GNU-only
  bad "--dry-run wrote into HOME: $(ls -A "$tmp/dry" | head -5 | tr '\n' ' ')"
fi
if grep -q 'would link' "$tmp/dry.out"; then ok "--dry-run printed its plan"; else bad "--dry-run printed no plan"; fi

# ── 2. a real run links what it says ─────────────────────────────────────────
# --links-only on BOTH real runs, deliberately: `make check` is defined as a hermetic
# links run (dotfiles-core's VENDORING.md), and this suite is what `make check`, `make test` and CI
# all reach. The starter bootstrap provisions nothing today, but the moment this repo
# adds the bootstrap_provision() hook it is expected to, a bare invocation here would
# install packages on the runner — and would be testing provisioning idempotency, not
# link idempotency.
mkdir -p "$tmp/home"
# The tmux plugin manager is the ONE network fetch in the wiring (the driver clones tpm
# into ~/.config/tmux/plugins when it is absent). This suite tests links, not GitHub —
# and it must pass offline and never leave a clone behind — so a placeholder stands in.
mkdir -p "$tmp/home/.config/tmux/plugins/tpm"
if ! HOME="$tmp/home" XDG_CONFIG_HOME="$tmp/home/.config" ./bootstrap.sh --links-only >"$tmp/run1.out" 2>&1; then
  bad "bootstrap.sh exited non-zero: $(cat "$tmp/run1.out")"
fi
CFG="$tmp/home/.config"
check_link() { # check_link <dest> <src>
  if [[ -L "$1" && "$(readlink "$1")" == "$2" ]]; then
    ok "${1#"$tmp/home/"} -> ${2#"$REPO/"}"
  else
    bad "${1#"$tmp/home/"} is not a symlink to ${2#"$REPO/"}"
  fi
}
# Repo-owned: always present, always linked.
check_link "$tmp/home/.zshenv" "$REPO/zsh/zshenv.zsh"
check_link "$CFG/zsh/.zprofile" "$REPO/zsh/zprofile.zsh"
# The interactive entry is the driver's: a managed ~/.zshrc (a real file carrying the
# v4 marker) and $ZDOTDIR/.zshrc seeded as a symlink to it — the shape every fleet repo
# on the driver has, and the one thing here that is written rather than linked.
if [[ -f "$tmp/home/.zshrc" && ! -L "$tmp/home/.zshrc" ]] && grep -q 'dotfiles-managed v4' "$tmp/home/.zshrc"; then
  ok ".zshrc is the managed v4 loader (written by the driver)"
else
  bad ".zshrc is missing, a symlink, or not the managed v4 loader"
fi
check_link "$CFG/zsh/.zshrc" "$tmp/home/.zshrc"
for f in "$REPO"/os/*.zsh; do [[ -e "$f" ]] && check_link "$CFG/zsh/80-os.zsh" "$f"; done
for f in "$REPO"/os/*.capabilities; do [[ -e "$f" ]] && check_link "$CFG/zsh/os.capabilities" "$f"; done
# The one Core file that is NOT optional: the scaffolded zshrc sources
# $ZDOTDIR/loader.zsh, so a core/ that exists but lacks zsh/loader.zsh boots a bare shell
# while bootstrap reports success. Require it before the conditional Core checks below.
if [[ -e "$REPO/core/zsh/loader.zsh" ]]; then
  check_link "$CFG/zsh/loader.zsh" "$REPO/core/zsh/loader.zsh"
else
  bad "core/zsh/loader.zsh is missing — the scaffolded zshrc sources it, so every shell would start bare"
fi
# The rest of Core is asserted when the vendored core/ carries the source (a core/
# vendored from an older Core may lack one), so the test never asserts a link
# bootstrap.sh would not have made. EVERY Core zsh
# module, both tmux files and the single configs — the whole link list bootstrap.sh
# carries, so dropping or breaking any link line there goes red here.
# The loader was asserted above; skip it here so each link is counted exactly once.
for f in "$REPO"/core/zsh/*.zsh; do
  [[ -e "$f" && "${f##*/}" != loader.zsh ]] && check_link "$CFG/zsh/$(basename "$f")" "$f"
done
for pair in "core/starship/starship.toml:$CFG/starship.toml" "core/tmux/tmux.conf:$CFG/tmux/tmux.conf" \
  "core/tmux/tmux.reset.conf:$CFG/tmux/tmux.reset.conf" "core/nvim:$CFG/nvim" \
  "core/git/gitconfig:$tmp/home/.gitconfig"; do
  src="$REPO/${pair%%:*}"
  dest="${pair#*:}"
  [[ -e "$src" ]] || continue
  check_link "$dest" "$src"
done
if [[ -f "$REPO/core/mise/config.toml" ]]; then
  # A regular file is not enough — an empty or stale one would pass as "seeded". The
  # copy must carry the seed's bytes. Compared by Git blob hash, not `cmp`: cmp ships in
  # diffutils, which a Tumbleweed box in this fleet did not have, and a missing cmp is
  # indistinguishable from "the files differ" (core/scripts/lib/common.sh has the story).
  _seed_hash="$(git hash-object "$REPO/core/mise/config.toml" 2>/dev/null)"
  _copy_hash="$(git hash-object "$CFG/mise/config.toml" 2>/dev/null)"
  if [[ -f "$CFG/mise/config.toml" && ! -L "$CFG/mise/config.toml" && -n "$_seed_hash" && "$_seed_hash" == "$_copy_hash" ]]; then
    ok "mise config is seeded as a COPY of core/mise/config.toml (a link would write \`mise use -g\` into core/)"
  else
    bad "mise config is missing, is a symlink into the vendored tree, or does not match the seed's bytes"
  fi
fi

# ── 3. the second run changes nothing ────────────────────────────────────────
# Three independent witnesses, because none alone is proof:
#   · The MUTATING COMMANDS the run invokes. The second run happens with a shim directory
#     first on PATH whose rm/ln/mv/cp/mkdir/chmod log their invocation and then exec the
#     real tool; an idempotent run invokes none of them. This is the primary witness — a
#     remove-and-recreate is seen as it happens, whatever the filesystem does with inodes.
#   · The TREE. Every entry under HOME — inode, mode, kind, link target, and for a regular
#     file its bytes — must be identical before and after. This catches what no wrapped
#     command performs: a file rewritten through a shell redirection keeps its inode but
#     not its checksum, and a mode changed through an absolute-path chmod keeps everything
#     but its mode string. `ls -ldi`, `readlink` and POSIX `cksum` are what GNU and BSD
#     share; no `-mindepth` (GNU) — the root row is dropped by name instead.
#   · WRITES. A rewrite with the SAME bytes is invisible to both of the above — no wrapped
#     command, and inode, mode, kind and checksum all survive — so a stamp file is touched
#     after the first run and `find -newer` (POSIX) must list nothing under HOME after
#     the second. One second is slept before that run: on a filesystem with 1-second
#     mtime resolution a rewrite inside the stamp's own second could otherwise hide.
# Output prefixes are the fourth, weakest claim, kept only as a message.
snapshot() { # snapshot <dir> → one line per entry: inode mode kind path [-> target | cksum]
  find "$1" -print | LC_ALL=C sort | while IFS= read -r p; do
    [[ "$p" == "$1" ]] && continue
    # shellcheck disable=SC2012  # the paths are ours (no odd names), and `find -printf` / `stat -c` are GNU-only
    ino_mode="$(ls -ldi "$p" | awk '{print $1, $2}')"   # no `--`: BSD ls; the paths are our own absolute sandbox paths
    if [[ -L "$p" ]]; then printf '%s L %s -> %s\n' "$ino_mode" "$p" "$(readlink "$p")"
    elif [[ -d "$p" ]]; then printf '%s D %s\n' "$ino_mode" "$p"
    else printf '%s F %s %s\n' "$ino_mode" "$p" "$(cksum <"$p" | awk '{print $1, $2}')"; fi
  done
}
# The rows that differ, without diffutils (a fleet host has been seen without `diff`;
# core/scripts/lib/common.sh records it): a two-pass awk set difference.
snapshot_delta() { # snapshot_delta <before> <after> → "> row" for rows gone, "< row" for rows new
  awk 'NR == FNR { seen[$0]; next } !($0 in seen) { print "> " $0 }' <(printf '%s\n' "$2") <(printf '%s\n' "$1")
  awk 'NR == FNR { seen[$0]; next } !($0 in seen) { print "< " $0 }' <(printf '%s\n' "$1") <(printf '%s\n' "$2")
}
mkdir -p "$tmp/shim"
: >"$tmp/mutations.log"
for cmd in rm ln mv cp mkdir chmod; do
  # Log, then hand off to the real tool — found by searching PATH with the shim dir
  # (its first entry) removed, so the wrapper never recurses into itself.
  cat >"$tmp/shim/$cmd" <<'SHIM'
#!/usr/bin/env bash
printf '%s %s\n' "${0##*/}" "$*" >>"$MUT_LOG"
PATH="${PATH#*:}" exec "${0##*/}" "$@"
SHIM
  chmod +x "$tmp/shim/$cmd"
done
before="$(snapshot "$tmp/home")"
: >"$tmp/stamp"
sleep 1
if ! HOME="$tmp/home" XDG_CONFIG_HOME="$tmp/home/.config" MUT_LOG="$tmp/mutations.log" PATH="$tmp/shim:$PATH" ./bootstrap.sh --links-only >"$tmp/run2.out" 2>&1; then
  bad "second bootstrap.sh run exited non-zero: $(cat "$tmp/run2.out")"
fi
after="$(snapshot "$tmp/home")"
written="$(find "$tmp/home" -newer "$tmp/stamp" -print)"
if [[ -s "$tmp/mutations.log" ]]; then
  bad "second run invoked mutating commands: $(head -4 "$tmp/mutations.log" | tr '\n' ';')"
elif [[ "$before" != "$after" ]]; then
  bad "second run changed the tree: $(snapshot_delta "$before" "$after" | head -4 | tr '\n' ' ')"
elif [[ -n "$written" ]]; then
  bad "second run rewrote files in place (same bytes, newer mtime): $(head -4 <<<"$written" | tr '\n' ' ')"
elif grep -Eq '^(linked|backed up|seeded) ' "$tmp/run2.out"; then
  bad "second run claims to have changed something: $(grep -E '^(linked|backed up|seeded) ' "$tmp/run2.out" | tr '\n' ' ')"
else
  ok "second run changed nothing (no rm/ln/mv/cp/mkdir/chmod invoked; every inode, mode, kind, link target and file checksum identical; nothing written after the stamp)"
fi

if ((rc == 0)); then
  printf '\033[32m✓\033[0m check-links: bootstrap.sh wires this repo and is idempotent\n'
fi
exit "$rc"
