#!/usr/bin/env bash
# bootstrap.sh — wire the vendored Core + the NixOS os/ layer into place. Idempotent.
# Generated by dotfiles-core/scripts/new-os-repo.sh — extend with NixOS provisioning.
#
# SHAPE: this file DECLARES what it is and DEFINES the hooks that are NixOS's, then hands
# over to Core's bootstrap driver, blib_main (core/lib/bootstrap-lib.sh, dotfiles-core#976):
# the flag loop, the escalator, the sudo keepalive, the Core symlink surface + the os/
# overlays, the managed ~/.zshrc loader, the login shell and the closing report run from
# that ONE definition. Add NixOS provisioning as a bootstrap_provision() hook (the driver runs
# it on a full run, under the keepalive, after resolving an escalator) and a
# bootstrap_guard() for the OS check; see any fleet repo's bootstrap.sh for the shape.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

# ── what this bootstrap IS (read by blib_main) ────────────────────────────────
# shellcheck disable=SC2034  # read by the vendored driver, which shellcheck cannot see
BOOTSTRAP_NAME="NixOS"
# shellcheck disable=SC2034
BOOTSTRAP_OS=nixos
# A starter provisions nothing and must not change the login shell: with no
# bootstrap_provision() hook and this off, the driver never resolves an escalator or
# primes a keepalive, so every run is unprivileged. Delete this line (or set it to 1)
# when the repo provisions and should switch the login shell to zsh like the fleet.
# shellcheck disable=SC2034
BOOTSTRAP_LOGIN_SHELL=0

# ── provisioning, when this repo grows it ────────────────────────────────────
# Define bootstrap_provision() and the driver runs it on a full run, under the keepalive,
# after resolving an escalator (priv/priv_run). On a STAGED host — an atomic (bootc) or
# transactional (MicroOS) edition, core/NON-MUTABLE-HOST-PROPOSAL.md §4 — the hook has one
# more branch, and dotfiles-Fedora's atomic variant is the reference shape:
#
#   IS_STAGED=0
#   [[ -e /run/ostree-booted ]] && IS_STAGED=1          # the HOST MARKER, never an os-release ID
#   [[ "${BOOTSTRAP_PROVISIONER:-}" == atomic ]] && IS_STAGED=1   # CI's seam: bootstrap-test.yml
#                                                     # `provisioner: atomic` forces it in a container
#   STAGED=0
#   bootstrap_provision() {
#     if ((IS_STAGED)); then
#       priv rpm-ostree install --idempotent "${pkgs[@]}" && STAGED=${#pkgs[@]}   # stages; live after reboot
#     else
#       priv dnf install -y "${pkgs[@]}"
#     fi
#   }
#   bootstrap_closing() {
#     ((STAGED)) && blib_warn "$STAGED package(s) layered into the next deployment — reboot to apply (sudo systemctl reboot), then re-run ./bootstrap.sh once"
#   }
#
# The closing line PRINTS the reboot verb and never runs it; the second run is "just re-run"
# (the guards the hook already has skip what the first run staged). Declare PROVISIONER /
# PKG_APPLY in os/<os>.capabilities beside it, so `up` and the nudge say the same sentence.

# The NixOS half of --help; the driver prints the shared flags after it. bootstrap_usage()
# is the ONE place a repo flag is documented — never a line range of this header, which
# drifts the moment a line is added above it. Add a flag: name it here, take it in
# bootstrap_flag() (see the driver's contract in core/lib/bootstrap-lib.sh).
# shellcheck disable=SC2329  # called by the vendored driver
bootstrap_usage() {
  cat <<'USAGE'
usage: bootstrap.sh [flags]

Wire the vendored Core + the NixOS os/ layer into place. Idempotent; safe to re-run
after every Core sync. This starter provisions nothing yet, so --links-only is what
every run does; the shared flags below are the driver's.
USAGE
}

# ── after the managed ~/.zshrc, before the login shell ────────────────────────
# The ZDOTDIR entry pair. ~/.zshenv points ZDOTDIR at ~/.config/zsh, where the driver
# has just seeded .zshrc as a symlink to the managed ~/.zshrc loader; .zprofile is this
# repo's login-time hook. Both .zsh sources, extensionless destinations (#451).
# shellcheck disable=SC2329
bootstrap_wire_post_loader() {
  blib_link "$DOTFILES/zsh/zshenv.zsh" "$HOME/.zshenv"
  blib_link "$DOTFILES/zsh/zprofile.zsh" "$CONFIG/zsh/.zprofile"
}

# ── vendored core/ present? (inline: can't source a lib out of core/ before this) ─
[[ -d "$DOTFILES/core" ]] || { echo "core/ subtree missing — run the subtree add first (VENDORING.md, one-time setup)" >&2; exit 1; }
for _req in core/zsh/loader.zsh core/lib/ux.sh core/lib/bootstrap-lib.sh; do
  [[ -e "$DOTFILES/$_req" ]] || { echo "vendored core/ missing or incomplete (need $_req) — run make sync in dotfiles-core" >&2; exit 1; }
done
unset _req
# shellcheck source=core/lib/ux.sh
source "$DOTFILES/core/lib/ux.sh"
# shellcheck source=core/lib/bootstrap-lib.sh
source "$DOTFILES/core/lib/bootstrap-lib.sh"

blib_main "$@"
