# Makefile — a discoverable façade over this repo's entry points.
# ──────────────────────────────────────────────────────────────────────────────
# Generated by dotfiles-core/scripts/new-os-repo.sh. Deliberately thin: it adds no logic
# beyond what CI already runs. `make lint` runs the BLOCKING legs of Core's reusable lint
# gate locally — shellcheck, bash -n, zsh -n, RETURN-trap discipline, the capability
# schema, markdownlint, actionlint, gitleaks and the Makefile-gate check — reading the
# SAME rules the gate reads: the vendored core/scripts/lib/common.sh scanners, Core's
# gitleaks.toml, this repo's .markdownlint.jsonc. The gate itself is called by
# .github/workflows/lint.yml (scaffolded beside this file), and it is the verdict: it
# installs and verifies PINNED tool versions (core/scripts/tool-versions.env) where these
# recipes use whatever is on PATH, and it also runs two legs not mirrored here: shfmt
# (advisory) and the Core-owned-block scan (blocking since #961). A leg whose tool is not
# installed SAYS SO and skips — never silently, and CI still runs it — so on a bare box the
# skips name what was not checked, and a local green is a strong prediction of the gate,
# not the gate.
#
# THE VERBS ARE THE FLEET'S, NOT THIS REPO'S. help / lint / check / dry-run /
# packages-check / core-verify / test are the canonical vocabulary every repo that vendors
# Core defines. Declared in dotfiles-core's scripts/make-vocabulary.txt; the contract is
# dotfiles-core's VENDORING.md § "The `make` vocabulary, and the test floor" — both live
# in the SOURCE repo only, neither is vendored into core/. Keep the canonical names; add
# your own targets and aliases beside them, never instead of them.
#
# NOT to be confused with dotfiles-core's own Makefile: that one exists in the SOURCE
# repo only — it is in neither core.manifest nor core.vendor, so no core/Makefile is ever
# vendored here — and its audit / sync / release targets would be meaningless from a
# vendored copy anyway. The vendored core/ is excluded from every check here — it is
# gated upstream — EXCEPT the secret scan, which covers the whole working tree exactly
# as the reusable gate's secrets leg does: a credential is a leak wherever it sits.
#
# A leg whose rule or policy the vendored Core does not carry yet SAYS SO and skips:
# _core_return_trap_hits arrived in v4.14.0, gitleaks.toml in v4.16.0,
# _core_make_gate_hits in v5.4.3, check-capabilities.sh in v4.19.0, and a pin as old
# as the v4.15.1 floor vendors none of them — a scan that ran anyway would pass on
# nothing, which is the failure mode this whole file is built against.
#
# Every guard sits on the same recipe line as the tool it guards (dotfiles-core#775):
# make runs each line in its own shell, so an `exit 0` on a line of its own skips nothing.
# ──────────────────────────────────────────────────────────────────────────────
.DEFAULT_GOAL := help
.PHONY: help lint shellcheck syntax zsh-syntax trap-guard capabilities markdownlint actionlint secrets make-gate check dry-run packages-check core-verify test

# Repo-owned shell only — core/ is gated upstream. Mirrors the reusable gate's pathspec.
SH_FILES  := $(shell git ls-files '*.sh' ':!:core/**' 2>/dev/null)
ZSH_FILES := $(shell git ls-files '*.zsh' ':!:core/**' 2>/dev/null)
MD_FILES  := $(shell git ls-files '*.md' ':!:core/**' 2>/dev/null)
# The vendored scanners `trap-guard` and `make-gate` source — the rules live in Core, once.
CORE_LIB  := core/scripts/lib/common.sh
# Identical to the reusable gate's env, so a local pass means a CI pass.
export SHELLCHECK_OPTS := -e SC1090 -e SC1091 -e SC2015 -e SC2088
# A sibling dotfiles-core checkout, for core-verify (override: make core-verify CORE_REPO=...)
CORE_REPO ?= $(CURDIR)/../dotfiles-core

help: ## Show this help
	@echo "$(notdir $(CURDIR)) — make targets:"
	@grep -E '^[a-z][a-zA-Z0-9_-]+:.*## ' $(MAKEFILE_LIST) \
		| sed -E 's/:.*## /\t/' | sort | awk -F'\t' '{printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

lint: shellcheck syntax zsh-syntax trap-guard capabilities markdownlint actionlint secrets make-gate ## The blocking legs of CI's lint gate, locally (a leg whose tool is absent says so and skips; CI pins the versions and is the verdict)
	@printf '\033[32m✓\033[0m lint clean\n'

shellcheck: ## ShellCheck the repo-owned bash, excluding the vendored core/ (skips without shellcheck; CI runs it)
	@# The skip, the empty-list branch and the run share ONE logical line: SH_FILES is
	@# `git ls-files`, so it is empty until the scaffold is committed, and a separate
	@# `exit 0` would end only its own line and let `shellcheck -x` run with no files.
	@if ! command -v shellcheck >/dev/null 2>&1; then echo "shellcheck not installed — skipped; CI runs it"; \
	elif test -z "$(SH_FILES)"; then echo "no repo-owned .sh tracked yet (git add first)"; \
	else echo "shellcheck -x $(SH_FILES)"; shellcheck -x $(SH_FILES); fi

syntax: ## bash -n the repo-owned bash, and check --help still works
	@if test -z "$(SH_FILES)"; then echo "no repo-owned .sh tracked yet (git add first)"; \
	else for f in $(SH_FILES); do echo "bash -n $$f"; bash -n "$$f" || exit 1; done; fi
	@bash bootstrap.sh --help >/dev/null || { echo "bootstrap.sh --help failed"; exit 1; }

zsh-syntax: ## zsh -n the repo-owned zsh (shellcheck has no zsh mode; skips without zsh)
	@if ! command -v zsh >/dev/null 2>&1; then echo "zsh not installed — skipping"; \
	elif test -z "$(ZSH_FILES)"; then echo "no repo-owned .zsh"; \
	else for f in $(ZSH_FILES); do echo "zsh -n $$f"; zsh -n "$$f" || exit 1; done; fi

trap-guard: ## Refuse a RETURN trap that does not disarm itself (shellcheck cannot see this; the rule is Core's _core_return_trap_hits)
	@# A bash RETURN trap is a GLOBAL slot, not a function-scoped one: armed inside a
	@# function it survives into the caller's frame and fires again on ITS return. Valid
	@# bash, so shellcheck and bash -n pass it — hence the dedicated scan, whose one
	@# definition is the vendored scanner. One logical line, like every leg here. The
	@# library rides in $0 (bash -c's first operand), so "$@" is exactly SH_FILES — no shift.
	@if test -z "$(SH_FILES)"; then echo "no repo-owned .sh tracked yet (git add first)"; \
	elif ! test -r "$(CORE_LIB)"; then echo "$(CORE_LIB) missing — vendor Core first"; exit 1; \
	else bash -c '. "$$0"; command -v _core_return_trap_hits >/dev/null 2>&1 || { echo "the vendored Core has no _core_return_trap_hits (older than v4.14.0) — skipped; CI runs it"; exit 0; }; rc=0; for f; do while IFS= read -r l; do [ -n "$$l" ] || continue; echo "$$f:$$l: a RETURN trap is armed without disarming itself"; rc=1; done < <(_core_return_trap_hits "$$f"); done; [ "$$rc" -eq 0 ] && echo "RETURN traps disarm themselves ($(words $(SH_FILES)) files)"; exit $$rc' "$(CORE_LIB)" $(SH_FILES); fi

capabilities: ## Validate os/*.capabilities against Core's schema (skips when the vendored validator predates v4.19.0; CI runs it)
	@# The validator arrived in Core v4.19.0; a pin between the v4.15.1 floor and that
	@# release vendors none, and the reusable gate's leg skips in that state — so does this.
	@# The glob is guarded: an unmatched glob stays LITERAL in sh, and a gate must never
	@# pass on nothing. --packages is passed only once install/packages.txt exists.
	@if ! test -x core/scripts/check-capabilities.sh; then echo "core/scripts/check-capabilities.sh not vendored (Core older than v4.19.0) — skipped; CI runs it"; \
	else rc=0; found=0; pk=""; [ -r install/packages.txt ] && pk="--packages install/packages.txt"; \
	for f in os/*.capabilities; do \
	  [ -e "$$f" ] || continue; found=1; \
	  core/scripts/check-capabilities.sh "$$f" $$pk || rc=1; \
	done; \
	if [ "$$found" -eq 0 ]; then echo "!! no os/*.capabilities — this repo must declare one (see core/examples/os.capabilities.example)"; rc=1; fi; \
	exit $$rc; fi

markdownlint: ## Lint repo-owned markdown against this repo's .markdownlint.jsonc (markdownlint-cli2 on PATH, else npx at Core's pinned version; skips without either)
	@if test -z "$(MD_FILES)"; then echo "no repo-owned .md tracked yet"; \
	elif command -v markdownlint-cli2 >/dev/null 2>&1; then markdownlint-cli2 $(MD_FILES); \
	elif command -v npx >/dev/null 2>&1; then v="$$(sed -n '/^MARKDOWNLINT_VERSION=/{s///p;q;}' core/scripts/tool-versions.env)"; npx --yes "markdownlint-cli2@$${v:-latest}" $(MD_FILES); \
	else echo "markdownlint-cli2 not installed (npm i -g markdownlint-cli2) — skipped; CI runs it"; fi

actionlint: ## Lint .github/workflows (skips without actionlint; CI runs it)
	@if ! command -v actionlint >/dev/null 2>&1; then echo "actionlint not installed — skipped; CI runs it"; else actionlint; fi

secrets: ## Scan the working tree for committed secrets against Core's ONE policy file (skips without gitleaks; CI runs it)
	@# -c core/gitleaks.toml: every repo measured the same way, no repo widening its own
	@# allowlist — the rule the reusable gate's secrets leg states.
	@if ! command -v gitleaks >/dev/null 2>&1; then echo "gitleaks not installed — skipped; CI runs it"; \
	elif ! test -r core/gitleaks.toml; then echo "core/gitleaks.toml not vendored (Core older than v4.16.0) — skipped; CI runs it"; \
	else gitleaks dir . -c core/gitleaks.toml --no-banner --redact; fi

make-gate: ## Every Makefile guard shares a line with its tool, and skips/fails as its help text says (Core's _core_make_gate_hits, dotfiles-core#775)
	@if ! test -r "$(CORE_LIB)"; then echo "$(CORE_LIB) missing — vendor Core first"; exit 1; \
	else bash -c '. "$$0"; command -v _core_make_gate_hits >/dev/null 2>&1 || { echo "the vendored Core has no _core_make_gate_hits (older than v5.4.3) — skipped; CI runs it"; exit 0; }; h="$$(_core_make_gate_hits .)" || { echo "_core_make_gate_hits failed to run"; exit 1; }; [ -z "$$h" ] || { printf "%s\n" "$$h"; exit 1; }; echo "every Makefile gate skips, fails and scopes as its help text claims"' "$(CORE_LIB)"; fi

check: lint ## lint + a hermetic links run against a throwaway HOME (test/check-links.sh)
	@./test/check-links.sh
	@./test/check-nix.sh

dry-run: ## Preview every link bootstrap would create; change nothing
	@./bootstrap.sh --dry-run

# A verb that does not apply is STUBBED, not absent, so `make packages-check` resolves in
# every repo (dotfiles-core's VENDORING.md). Replace this the day install/packages.txt exists —
# dotfiles-Debian/test/check-packages.sh is the model for a real resolver.
packages-check: ## Resolve every package name (stub until this repo has a package list)
	@echo "packages-check: not applicable to this repo (no OS package list yet)"

core-verify: ## Verify the vendored core/ is pristine vs core.lock (needs CORE_REPO)
	@[ -x "$(CORE_REPO)/scripts/core-integrity.sh" ] || { echo "need a dotfiles-core checkout at CORE_REPO=$(CORE_REPO)"; exit 1; }
	@"$(CORE_REPO)/scripts/core-integrity.sh" --self "$(CURDIR)"

# EXPLICIT PATHS, not a test/*.sh loop: the fleet's suite-detection register credits a
# named script, and a glob would also silently pick up a scratch file. check-nix.sh skips
# without nix (the normal case off a NixOS box) — the nix-parse job in
# .github/workflows/test.yml is where the parse actually runs.
test: ## Run this repo's own suite (test/)
	@./test/check-links.sh
	@./test/check-nix.sh
